spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/datacenter?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driverClass: com.mysql.cj.jdbc.Driver


  jpa:
    dialect: com.fosung.framework.dao.dialect.PostgreSQL9DialectWithoutFK
    schema: public
    show-sql: true



server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
